let Channel5g = {
  "one": [36, 40, 44, 48, 149, 153, 157, 161, 165],
  "two": [36, 40, 44, 48, 149, 153, 157, 161], //US,CA,MX,KR,
  "three": [149, 153, 157, 161, 165], //MY
  "four": [149, 153, 157, 161],
  "five": [36, 40, 44, 48], //JP,GB,DE,EU,AF,IT,ES
  "notsupport": [] //not support 5G
}

let countryCodeALL = {
  AR: ['ARGENTINA', 13, Channel5g.four],
  AM: ['ARMENIA', 13, Channel5g.five],
  AU: ['AUSTRALIA', 13, Channel5g.one],
  AT: ['AUSTRIA', 13, Channel5g.five],
  AZ: ['AZERBAIJAN', 13, Channel5g.five],
  BH: ['BAHRAIN', 13, Channel5g.one],
  BY: ['BELARUS', 13, Channel5g.five],
  BE: ['BELGIUM', 13, Channel5g.five],
  BZ: ['BELIZE', 13, Channel5g.three],
  BO: ['BOLIVIA', 13, Channel5g.three],
  BR: ['BRAZIL', 13, Channel5g.one],
  BN: ['BRUNEI DARUSSALAM', 13, Channel5g.three],
  BG: ['BULGARIA', 13, Channel5g.five],
  CA: ['CANADA', 11, Channel5g.one],
  CL: ['CHILE', 13, Channel5g.one],
  CN: ['CHINA', 13, Channel5g.one],
  CO: ['COLOMBIA', 11, Channel5g.one],
  CR: ['COSTA RICA', 11, Channel5g.notsupport],
  HR: ['CROATIA', 13, Channel5g.five],
  CY: ['CYPRUS', 13, Channel5g.five],
  CZ: ['THE CZECH REPUBLIC', 13, Channel5g.five],
  DK: ['DENMARK', 13, Channel5g.five],
  DO: ['DOMINICAN REPUBLIC', 11, Channel5g.one],
  EC: ['ECUADOR', 13, Channel5g.one],
  EG: ['EGYPT', 13, Channel5g.five],
  SV: ['EL SALVADOR', 11, Channel5g.notsupport],
  EE: ['ESTONIA', 13, Channel5g.five],
  FI: ['FINLAND', 13, Channel5g.five],
  FR: ['FRANCE', 13, Channel5g.five],
  GE: ['GEORGIA', 13, Channel5g.five],
  DE: ['GERMANY', 13, Channel5g.five],
  GR: ['GREECE', 13, Channel5g.five],
  GT: ['GUATEMALA', 11, Channel5g.one],
  HN: ['HONDURAS', 11, Channel5g.one],
  HK: ['HONG KONG', 13, Channel5g.one],
  HU: ['HUNGARY', 13, Channel5g.five],
  IS: ['ICELAND', 13, Channel5g.five],
  IN: ['INDIA', 13, Channel5g.one],
  ID: ['INDONESIA', 13, Channel5g.three],
  IR: ['IRAN', 13, Channel5g.three],
  IQ: ['IRAQ', 13, Channel5g.one],
  IE: ['IRELAND', 13, Channel5g.five],
  IL: ['ISRAEL', 13, Channel5g.five],
  IT: ['ITALY', 13, Channel5g.five],
  JP: ['JAPAN', 13, Channel5g.five],
  JO: ['JORDAN', 13, Channel5g.five],
  KZ: ['KAZAKHSTAN', 13, Channel5g.notsupport],
  KR: ['KOREA REPUBLIC', 13, Channel5g.four],
  KW: ['KUWAIT', 13, Channel5g.notsupport],
  LV: ['LATVIA', 13, Channel5g.five],
  LB: ['LEBANON', 13, Channel5g.three],
  LI: ['LIECHTENSTEIN', 13, Channel5g.five],
  LT: ['LITHUANIA', 13, Channel5g.five],
  LU: ['LUXEMBOURG', 13, Channel5g.five],
  MO: ['MACAU', 13, Channel5g.one],
  MK: ['MACEDONIA', 13, Channel5g.five],
  MY: ['MALAYSIA', 13, Channel5g.three],
  MT: ['MALTA', 13, Channel5g.five],
  MX: ['MEXICO', 11, Channel5g.one],
  MC: ['MONACO', 13, Channel5g.five],
  MA: ['MOROCCO', 13, Channel5g.notsupport],
  NL: ['NETHERLANDS', 13, Channel5g.five],
  NZ: ['NEW ZEALAND', 13, Channel5g.one],
  NG: ['NIGERIA', 13, Channel5g.one],
  KP: ['NORTH KOREA', 13, Channel5g.four],
  NO: ['NORWAY', 13, Channel5g.five],
  OM: ['OMAN', 13, Channel5g.one],
  PK: ['PAKISTAN', 13, Channel5g.four],
  PA: ['PANAMA', 11, Channel5g.one],
  PE: ['PERU', 13, Channel5g.three],
  PH: ['PHILIPPINES', 13, Channel5g.one],
  PL: ['POLAND', 13, Channel5g.five],
  PT: ['PORTUGAL', 13, Channel5g.five],
  PR: ['PUERTO RICO', 11, Channel5g.one],
  QA: ['QATAR', 13, Channel5g.notsupport],
  RO: ['ROMANIA', 13, Channel5g.five],
  RU: ['RUSSIA', 13, Channel5g.two],
  SA: ['SAUDIA ARABIA', 13, Channel5g.one],
  SG: ['SINGAPORE', 13, Channel5g.one],
  SK: ['SLOVAK REPUBLIC', 13, Channel5g.five],
  SI: ['SLOVENIA', 13, Channel5g.five],
  ZA: ['SOUTH AFRICA', 13, Channel5g.one],
  ES: ['ESPAÑA', 13, Channel5g.five],
  LK: ['SRI LANKA', 13, Channel5g.one],
  SE: ['SWEDEN', 13, Channel5g.five],
  CH: ['SWITZERLAND', 13, Channel5g.five],
  SY: ['SYRIA', 13, Channel5g.notsupport],
  TW: ['TAIWAN, PROVINCE OF CHINA', 11, Channel5g.three],
  TH: ['THAILAND', 13, Channel5g.one],
  TT: ['TRINIDAD & TOBAGO', 13, Channel5g.one],
  TN: ['TUNISIA', 13, Channel5g.five],
  TR: ['TURKEY', 13, Channel5g.five],
  UA: ['UKRAINE', 13, Channel5g.notsupport],
  AE: ['UNITED ARAB EMIRATES', 13, Channel5g.five],
  GB: ['UNITED KINGDOM', 13, Channel5g.five],
  US: ['UNITED STATES', 11, Channel5g.one],
  UY: ['URUGUAY', 13, Channel5g.one],
  UZ: ['UZBEKISTAN', 11, Channel5g.one],
  VE: ['VENEZUELA', 13, Channel5g.three],
  VN: ['VIETNAM', 13, Channel5g.five],
  YE: ['YEMEN', 13, Channel5g.notsupport],
  ZW: ['ZIMBABWE', 13, Channel5g.notsupport],
  DZ: ['Algeria', 13, Channel5g.notsupport],
  CG: ['Congo', 13, Channel5g.five],
  TZ: ['Tanzania', 13, Channel5g.five],
  GH: ['GHANA', 13, Channel5g.notsupport],
  GA: ['Gabon', 13, Channel5g.one],
  KE: ['Kenya', 13, Channel5g.five],
  LR: ['Liberia', 13, Channel5g.five],
  AL: ['Albania', 13, Channel5g.notsupport],
  FJ: ['Fiji', 13, Channel5g.notsupport],
  MZ: ['Mozambique', 13, Channel5g.notsupport],
  LS: ['Lesotho', 13, Channel5g.notsupport],
  ST: ['SAO TOME AND PRINCIPE', 13, Channel5g.notsupport],
  BS: ['Bahamas', 11, Channel5g.notsupport],
  CU: ['Cuba', 11, Channel5g.notsupport],
  RS: ['SERBIA', 13, Channel5g.five],
  MNE: ['Montenegro', 13, Channel5g.five],
  NE: ['NIGER', 13, Channel5g.one],
  JM: ['Jamaica', 11, Channel5g.notsupport],
  NI: ['Nicaragua', 11, Channel5g.notsupport]
}

let defaultCountryCodeList = [
  "CN",
  "US", 
  "JP",
  "CA",
  "MX",
  "DE",
  "GB",
  "IN",
  "IL",
  "KR",
  "MY",
  "RU",
  "SG",
  "TW",
  "CZ",
  "FR",
  "ES",
  "IT",
  "SK",
  "PT",
  "RO",
  "ZA",
  "AU",
  "DO"
]

export {
  countryCodeALL,
  defaultCountryCodeList
}