/*
全局变量
*/
let langListAll = {
  al: 'Shqipe',
  ar: 'العربية',
  br: 'Português(Brasil)',
  bu: 'български',
  ch: '简体中文',
  du: 'Nederlands',
  en: 'English',
  en_uk: 'English(UK)',
  en_us: 'English(US)',
  fr: 'Français',
  de: 'Deutsch',
  gk: 'Ελληνικά',
  hg: 'Magyar',
  it: 'Italiano',
  ja: '日本語',
  mk: 'Македонија',
  pg: 'Português(Portugal)',
  po: 'Polski',
  ro: 'Română',
  ru: 'Русский',
  sp: 'Español',
  sp_latam: 'Español(Latam)',
  sr: 'Srpski',
  tw: '繁體中文',
  ur: 'Українська',
  da: 'Dansk',
  kz: 'Қазақша',
  kr: '한글',
  th: 'ไทย',
  cs: 'čeština',
  hr: 'Hrvatski',
  se: 'Sverige',
  sk: 'Slovensko',
  wr: 'اردو',
  vi: 'Vietnamese',
  tr: 'Turkish',
  si: 'Slovenian',
  fi: 'Suomi',
  no: 'Norge',
  ee: 'eesti',
  fa: 'فارسی',
  lv: 'Latvijas',
  lt: 'Lietuvos',
  id: 'Indonesia'
};

export default langListAll;
