/*
全局变量
*/
let sys = {};

/*TimeZone*/
sys.TimeZone = [
  ["UTC", "UTC", "ids_timeZone_UTC", "(UTC+00:00)"],
  ["WET0WEST,M3.5.0/1,M10.5.0", "Atlantic/Faroe", "ids_timeZone_AtlanticFaroe", "(UTC+00:00)"],
  ["NFT-11:30", "Pacific/Norfolk", "ids_timeZone_PacificNorfolk", "(UTC+11:30)"],
  ["ART3", "America/Argentina/Cordoba", "ids_timeZone_AmericaArgentinaCordoba", "(UTC-03:00)"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4", "Europe/Simferopol", "ids_timeZone_EuropeSimferopol", "(UTC+02:00)"],
  ["WST-8", "Antarctica/Casey", "ids_timeZone_AntarcticaCasey", "(UTC+08:00)"],
  ["ART3", "America/Argentina/La Rioja", "ids_timeZone_AmericaArgentinaLaRioja", "(UTC-03:00)"],
  ["BTT-6", "Asia/Thimphu", "ids_timeZone_AsiaThimphu", "(UTC+06:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Budapest", "ids_timeZone_EuropeBudapest", "(UTC+01:00)"],
  ["SYOT-3", "Antarctica/Syowa", "ids_timeZone_AntarcticaSyowa", "(UTC+03:00)"],
  ["CST6", "America/El Salvador", "ids_timeZone_AmericaElSalvador", "(UTC-06:00)"],
  ["SCT-4", "Indian/Mahe", "ids_timeZone_IndianMahe", "(UTC+04:00)"],
  ["MST7MDT,M3.2.0,M11.1.0", "America/Boise", "ids_timeZone_AmericaBoise", "(UTC-07:00)"],
  ["AST4", "America/St Thomas", "ids_timeZone_AmericaStThomas", "(UTC-04:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Gibraltar", "ids_timeZone_EuropeGibraltar", "(UTC+01:00)"],
  ["WST-13", "Pacific/Apia", "ids_timeZone_PacificApia", "(UTC+13:00)"],
  ["FET-3", "Europe/Minsk", "ids_timeZone_EuropeMinsk", "(UTC+03:00)"],
  ["CKT10", "Pacific/Rarotonga", "ids_timeZone_PacificRarotonga", "(UTC-10:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Arctic/Longyearbyen", "ids_timeZone_ArcticLongyearbyen", "(UTC+01:00)"],
  ["CST-8", "Asia/Shanghai", "ids_timeZone_AsiaShanghai", "(UTC+08:00)"],
  ["CST6CDT,M3.2.0,M11.1.0", "America/North Dakota/New Salem", "ids_timeZone_AmericaNorthDakotaNewSalem", "(UTC-06:00)"],
  ["EET-2", "Africa/Tripoli", "ids_timeZone_AfricaTripoli", "(UTC+02:00)"],
  ["PET5", "America/Lima", "ids_timeZone_AmericaLima", "(UTC-05:00)"],
  ["AMT4", "America/Rio Branco", "ids_timeZone_AmericaRioBranco", "(UTC-04:00)"],
  ["WAT-1", "Africa/Libreville", "ids_timeZone_AfricaLibreville", "(UTC+01:00)"],
  ["PONT-11", "Pacific/Pohnpei", "ids_timeZone_PacificPohnpei", "(UTC+11:00)"],
  ["GMT0IST,M3.5.0/1,M10.5.0", "Europe/Dublin", "ids_timeZone_EuropeDublin", "(UTC+00:00)"],
  ["HAST10HADT,M3.2.0,M11.1.0", "America/Adak", "ids_timeZone_AmericaAdak", "(UTC-10:00)"],
  ["QYZT-6", "Asia/Qyzylorda", "ids_timeZone_AsiaQyzylorda", "(UTC+06:00)"],
  ["IOT-6", "Indian/Chagos", "ids_timeZone_IndianChagos", "(UTC+06:00)"],
  ["MYT-8", "Asia/Kuching", "ids_timeZone_AsiaKuching", "(UTC+08:00)"],
  ["FET-3", "Europe/Kaliningrad", "ids_timeZone_EuropeKaliningrad", "(UTC+03:00)"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4", "Europe/Sofia", "ids_timeZone_EuropeSofia", "(UTC+02:00)"],
  ["CST-8", "Asia/Taipei", "ids_timeZone_AsiaTaipei", "(UTC+08:00)"],
  ["PST8PDT,M3.2.0,M11.1.0", "America/Dawson", "ids_timeZone_AmericaDawson", "(UTC-08:00)"],
  ["GMT0", "Africa/Banjul", "ids_timeZone_AfricaBanjul", "(UTC+00:00)"],
  ["AMT4AMST,M10.3.0/0,M2.3.0/0", "America/Campo Grande", "ids_timeZone_AmericaCampoGrande", "(UTC-04:00)"],
  ["CAT-2", "Africa/Blantyre", "ids_timeZone_AfricaBlantyre", "(UTC+02:00)"],
  ["CST6CDT,M3.2.0,M11.1.0", "America/Rankin Inlet", "ids_timeZone_AmericaRankinInlet", "(UTC-06:00)"],
  ["CAT-2", "Africa/Bujumbura", "ids_timeZone_AfricaBujumbura", "(UTC+02:00)"],
  ["WAT-1", "Africa/Luanda", "ids_timeZone_AfricaLuanda", "(UTC+01:00)"],
  ["AST4", "America/Marigot", "ids_timeZone_AmericaMarigot", "(UTC-04:00)"],
  ["GMT0", "Atlantic/St Helena", "ids_timeZone_AtlanticStHelena", "(UTC+00:00)"],
  ["ALMT-6", "Asia/Almaty", "ids_timeZone_AsiaAlmaty", "(UTC+06:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Vaduz", "ids_timeZone_EuropeVaduz", "(UTC+01:00)"],
  ["MST7MDT,M3.2.0,M11.1.0", "America/Inuvik", "ids_timeZone_AmericaInuvik", "(UTC-07:00)"],
  ["EET-2", "Asia/Hebron", "ids_timeZone_AsiaHebron", "(UTC+02:00)"],
  ["MST7MDT,M4.1.0,M10.5.0", "America/Mazatlan", "ids_timeZone_AmericaMazatlan", "(UTC-07:00)"],
  ["AST4", "America/Curacao", "ids_timeZone_AmericaCuracao", "(UTC-04:00)"],
  ["WAT-1", "Africa/Ndjamena", "ids_timeZone_AfricaNdjamena", "(UTC+01:00)"],
  ["AST-3", "Asia/Kuwait", "ids_timeZone_AsiaKuwait", "(UTC+03:00)"],
  ["GMT0", "Africa/Nouakchott", "ids_timeZone_AfricaNouakchott", "(UTC+00:00)"],
  ["ROTT3", "Antarctica/Rothera", "ids_timeZone_AntarcticaRothera", "(UTC-03:00)"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4", "Europe/Uzhgorod", "ids_timeZone_EuropeUzhgorod", "(UTC+02:00)"],
  ["GMT0", "Africa/Bamako", "ids_timeZone_AfricaBamako", "(UTC+00:00)"],
  ["MST7", "America/Phoenix", "ids_timeZone_AmericaPhoenix", "(UTC-07:00)"],
  ["CST6", "America/Costa Rica", "ids_timeZone_AmericaCostaRica", "(UTC-06:00)"],
  ["GST2", "Atlantic/South Georgia", "ids_timeZone_AtlanticSouthGeorgia", "(UTC-02:00)"],
  ["MHT-12", "Pacific/Majuro", "ids_timeZone_PacificMajuro", "(UTC+12:00)"],
  ["EST5", "America/Port-au-Prince", "ids_timeZone_AmericaPortAuPrince", "(UTC-05:00)"],
  ["YEKT-6", "Asia/Yekaterinburg", "ids_timeZone_AsiaYekaterinburg", "(UTC+06:00)"],
  ["CST-8", "Asia/Kashgar", "ids_timeZone_AsiaKashgar", "(UTC+08:00)"],
  ["CET-1", "Africa/Algiers", "ids_timeZone_AfricaAlgiers", "(UTC+01:00)"],
  ["AMT4", "America/Eirunepe", "ids_timeZone_AmericaEirunepe", "(UTC-04:00)"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4", "Europe/Vilnius", "ids_timeZone_EuropeVilnius", "(UTC+02:00)"],
  ["WET0", "Africa/Casablanca", "ids_timeZone_AfricaCasablanca", "(UTC+00:00)"],
  ["ANAT-12", "Asia/Anadyr", "ids_timeZone_AsiaAnadyr", "(UTC+12:00)"],
  ["MST7MDT,M3.2.0,M11.1.0", "America/Edmonton", "ids_timeZone_AmericaEdmonton", "(UTC-07:00)"],
  ["WET0", "Africa/El Aaiun", "ids_timeZone_AfricaElAaiun", "(UTC+00:00)"],
  ["WET0WEST,M3.5.0/1,M10.5.0", "Atlantic/Canary", "ids_timeZone_AtlanticCanary", "(UTC+00:00)"],
  ["ART3", "America/Argentina/Rio Gallegos", "ids_timeZone_AmericaArgentinaRioGallegos", "(UTC-03:00)"],
  ["ART3", "America/Argentina/Ushuaia", "ids_timeZone_AmericaArgentinaUshuaia", "(UTC-03:00)"],
  ["MST7MDT,M3.2.0,M11.1.0", "America/Denver", "ids_timeZone_AmericaDenver", "(UTC-07:00)"],
  ["PHOT-13", "Pacific/Enderbury", "ids_timeZone_PacificEnderbury", "(UTC+13:00)"],
  ["CST6CDT,M3.2.0,M11.1.0", "America/Resolute", "ids_timeZone_AmericaResolute", "(UTC-06:00)"],
  ["AST4ADT,M3.2.0,M11.1.0", "America/Goose Bay", "ids_timeZone_AmericaGooseBay", "(UTC-04:00)"],
  ["CST6", "America/Regina", "ids_timeZone_AmericaRegina", "(UTC-06:00)"],
  ["CST-8", "Asia/Macau", "ids_timeZone_AsiaMacau", "(UTC+08:00)"],
  ["EAT-3", "Africa/Dar es Salaam", "ids_timeZone_AfricaDarEsSalaam", "(UTC+03:00)"],
  ["WAT-1", "Africa/Kinshasa", "ids_timeZone_AfricaKinshasa", "(UTC+01:00)"],
  ["CST6CDT,M4.1.0,M10.5.0", "America/Bahia Banderas", "ids_timeZone_AmericaBahiaBanderas", "(UTC-06:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Madrid", "ids_timeZone_EuropeMadrid", "(UTC+01:00)"],
  ["TLT-9", "Asia/Dili", "ids_timeZone_AsiaDili", "(UTC+09:00)"],
  ["MAWT-5", "Antarctica/Mawson", "ids_timeZone_AntarcticaMawson", "(UTC+05:00)"],
  ["MST7MDT,M3.2.0,M11.1.0", "America/Ojinaga", "ids_timeZone_AmericaOjinaga", "(UTC-07:00)"],
  ["NUT11", "Pacific/Niue", "ids_timeZone_PacificNiue", "(UTC-11:00)"],
  ["AST4", "America/Anguilla", "ids_timeZone_AmericaAnguilla", "(UTC-04:00)"],
  ["WAT-1", "Africa/Bangui", "ids_timeZone_AfricaBangui", "(UTC+01:00)"],
  ["CXT-7", "Indian/Christmas", "ids_timeZone_IndianChristmas", "(UTC+07:00)"],
  ["MVT-5", "Indian/Maldives", "ids_timeZone_IndianMaldives", "(UTC+05:00)"],
  ["AST4", "America/Barbados", "ids_timeZone_AmericaBarbados", "(UTC-04:00)"],
  ["PETT-12", "Asia/Kamchatka", "ids_timeZone_AsiaKamchatka", "(UTC+12:00)"],
  ["GFT3", "America/Cayenne", "ids_timeZone_AmericaCayenne", "(UTC-03:00)"],
  ["VOLT-4", "Europe/Volgograd", "ids_timeZone_EuropeVolgograd", "(UTC+04:00)"],
  ["AST4", "America/St Lucia", "ids_timeZone_AmericaStLucia", "(UTC-04:00)"],
  ["CWST-8:45", "Australia/Eucla", "ids_timeZone_AustraliaEucla", "(UTC+08:45)"],
  ["LINT-14", "Pacific/Kiritimati", "ids_timeZone_PacificKiritimati", "(UTC+14:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Sarajevo", "ids_timeZone_EuropeSarajevo", "(UTC+01:00)"],
  ["MST7", "America/Dawson Creek", "ids_timeZone_AmericaDawsonCreek", "(UTC-07:00)"],
  ["AST4", "America/Antigua", "ids_timeZone_AmericaAntigua", "(UTC-04:00)"],
  ["CET-1", "Africa/Tunis", "ids_timeZone_AfricaTunis", "(UTC+01:00)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Indiana/Vevay", "ids_timeZone_AmericaIndianaVevay", "(UTC-05:00)"],
  ["EAT-3", "Africa/Asmara", "ids_timeZone_AfricaAsmara", "(UTC+03:00)"],
  ["AQTT-5", "Asia/Aqtobe", "ids_timeZone_AsiaAqtobe", "(UTC+05:00)"],
  ["KOST-11", "Pacific/Kosrae", "ids_timeZone_PacificKosrae", "(UTC+11:00)"],
  ["CVT1", "Atlantic/Cape Verde", "ids_timeZone_AtlanticCapeVerde", "(UTC-01:00)"],
  ["GMT0", "Africa/Lome", "ids_timeZone_AfricaLome", "(UTC+00:00)"],
  ["CHOT-8", "Asia/Choibalsan", "ids_timeZone_AsiaChoibalsan", "(UTC+08:00)"],
  ["WIT-7", "Asia/Jakarta", "ids_timeZone_AsiaJakarta", "(UTC+07:00)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Indiana/Winamac", "ids_timeZone_AmericaIndianaWinamac", "(UTC-05:00)"],
  ["AKST9AKDT,M3.2.0,M11.1.0", "America/Yakutat", "ids_timeZone_AmericaYakutat", "(UTC-09:00)"],
  ["AST4", "America/Dominica", "ids_timeZone_AmericaDominica", "(UTC-04:00)"],
  ["CST6CDT,M3.2.0,M11.1.0", "America/Rainy River", "ids_timeZone_AmericaRainyRiver", "(UTC-06:00)"],
  ["CST6", "America/Belize", "ids_timeZone_AmericaBelize", "(UTC-06:00)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Indiana/Vincennes", "ids_timeZone_AmericaIndianaVincennes", "(UTC-05:00)"],
  ["ORAT-5", "Asia/Oral", "ids_timeZone_AsiaOral", "(UTC+05:00)"],
  ["TOT-13", "Pacific/Tongatapu", "ids_timeZone_PacificTongatapu", "(UTC+13:00)"],
  ["BRT3", "America/Recife", "ids_timeZone_AmericaRecife", "(UTC-03:00)"],
  ["ChST-10", "Pacific/Guam", "ids_timeZone_PacificGuam", "(UTC+10:00)"],
  ["CST-8", "Asia/Chongqing", "ids_timeZone_AsiaChongqing", "(UTC+08:00)"],
  ["TMT-5", "Asia/Ashgabat", "ids_timeZone_AsiaAshgabat", "(UTC+05:00)"],
  ["BRT3", "America/Fortaleza", "ids_timeZone_AmericaFortaleza", "(UTC-03:00)"],
  ["CST6CDT,M3.2.0,M11.1.0", "America/Indiana/Tell City", "ids_timeZone_AmericaIndianaTellCity", "(UTC-06:00)"],
  ["AST4", "America/St Barthelemy", "ids_timeZone_AmericaStBarthelemy", "(UTC-04:00)"],
  ["ICT-7", "Asia/Bangkok", "ids_timeZone_AsiaBangkok", "(UTC+07:00)"],
  ["WAT-1WAST,M9.1.0,M4.1.0", "Africa/Windhoek", "ids_timeZone_AfricaWindhoek", "(UTC+01:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Podgorica", "ids_timeZone_EuropePodgorica", "(UTC+01:00)"],
  ["EGT1EGST,M3.5.0/0,M10.5.0/1", "America/Scoresbysund", "ids_timeZone_AmericaScoresbysund", "(UTC-01:00)"],
  ["WAT-1", "Africa/Lagos", "ids_timeZone_AfricaLagos", "(UTC+01:00)"],
  ["MST7MDT,M3.2.0,M11.1.0", "America/Cambridge Bay", "ids_timeZone_AmericaCambridgeBay", "(UTC-07:00)"],
  ["CAT-2", "Africa/Gaborone", "ids_timeZone_AfricaGaborone", "(UTC+02:00)"],
  ["AST4", "America/Port of Spain", "ids_timeZone_AmericaPortOfSpain", "(UTC-04:00)"],
  ["WAT-1", "Africa/Malabo", "ids_timeZone_AfricaMalabo", "(UTC+01:00)"],
  ["CST6CDT,M3.2.0,M11.1.0", "America/Menominee", "ids_timeZone_AmericaMenominee", "(UTC-06:00)"],
  ["EAT-3", "Africa/Djibouti", "ids_timeZone_AfricaDjibouti", "(UTC+03:00)"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4", "Europe/Mariehamn", "ids_timeZone_EuropeMariehamn", "(UTC+02:00)"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4", "Europe/Riga", "ids_timeZone_EuropeRiga", "(UTC+02:00)"],
  ["ART3", "America/Argentina/Salta", "ids_timeZone_AmericaArgentinaSalta", "(UTC-03:00)"],
  ["MST7MDT,M3.2.0,M11.1.0", "America/Shiprock", "ids_timeZone_AmericaShiprock", "(UTC-07:00)"],
  ["AST-3", "Asia/Qatar", "ids_timeZone_AsiaQatar", "(UTC+03:00)"],
  ["AST4", "America/Guadeloupe", "ids_timeZone_AmericaGuadeloupe", "(UTC-04:00)"],
  ["WFT-12", "Pacific/Wallis", "ids_timeZone_PacificWallis", "(UTC+12:00)"],
  ["CST6", "America/Guatemala", "ids_timeZone_AmericaGuatemala", "(UTC-06:00)"],
  ["WAKT-12", "Pacific/Wake", "ids_timeZone_PacificWake", "(UTC+12:00)"],
  ["AST4ADT,M3.2.0,M11.1.0", "America/Moncton", "ids_timeZone_AmericaMoncton", "(UTC-04:00)"],
  ["PMST3PMDT,M3.2.0,M11.1.0", "America/Miquelon", "ids_timeZone_AmericaMiquelon", "(UTC-03:00)"],
  ["TAHT10", "Pacific/Tahiti", "ids_timeZone_PacificTahiti", "(UTC-10:00)"],
  ["CST6CDT,M4.1.0,M10.5.0", "America/Monterrey", "ids_timeZone_AmericaMonterrey", "(UTC-06:00)"],
  ["AST4", "America/Tortola", "ids_timeZone_AmericaTortola", "(UTC-04:00)"],
  ["ChST-10", "Pacific/Saipan", "ids_timeZone_PacificSaipan", "(UTC+10:00)"],
  ["AST4ADT,M3.2.0,M11.1.0", "America/Thule", "ids_timeZone_AmericaThule", "(UTC-04:00)"],
  ["EET-2EEST,M3.5.0/0,M10.5.0/0", "Asia/Beirut", "ids_timeZone_AsiaBeirut", "(UTC+02:00)"],
  ["AST4", "America/Aruba", "ids_timeZone_AmericaAruba", "(UTC-04:00)"],
  ["MUT-4", "Indian/Mauritius", "ids_timeZone_IndianMauritius", "(UTC+04:00)"],
  ["PGT-10", "Pacific/Port Moresby", "ids_timeZone_PacificPortMoresby", "(UTC+10:00)"],
  ["MST7MDT,M3.2.0,M11.1.0", "America/Yellowknife", "ids_timeZone_AmericaYellowknife", "(UTC-07:00)"],
  ["OMST-7", "Asia/Omsk", "ids_timeZone_AsiaOmsk", "(UTC+07:00)"],
  ["CST-9:30", "Australia/Darwin", "ids_timeZone_AustraliaDarwin", "(UTC+09:30)"],
  ["PWT-9", "Pacific/Palau", "ids_timeZone_PacificPalau", "(UTC+09:00)"],
  ["GMT0", "Africa/Sao Tome", "ids_timeZone_AfricaSaoTome", "(UTC+00:00)"],
  ["NCT-11", "Pacific/Noumea", "ids_timeZone_PacificNoumea", "(UTC+11:00)"],
  ["AZOT1AZOST,M3.5.0/0,M10.5.0/1", "Atlantic/Azores", "ids_timeZone_AtlanticAzores", "(UTC-01:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Paris", "ids_timeZone_EuropeParis", "(UTC+01:00)"],
  ["NRT-12", "Pacific/Nauru", "ids_timeZone_PacificNauru", "(UTC+12:00)"],
  ["SST11", "Pacific/Midway", "ids_timeZone_PacificMidway", "(UTC-11:00)"],
  ["KST-9", "Asia/Seoul", "ids_timeZone_AsiaSeoul", "(UTC+09:00)"],
  ["WST-8", "Australia/Perth", "ids_timeZone_AustraliaPerth", "(UTC+08:00)"],
  ["PYT4PYST,M10.1.0/0,M4.2.0/0", "America/Asuncion", "ids_timeZone_AmericaAsuncion", "(UTC-04:00)"],
  ["MHT-12", "Pacific/Kwajalein", "ids_timeZone_PacificKwajalein", "(UTC+12:00)"],
  ["AST-3", "Asia/Bahrain", "ids_timeZone_AsiaBahrain", "(UTC+03:00)"],
  ["AST-3", "Asia/Baghdad", "ids_timeZone_AsiaBaghdad", "(UTC+03:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Malta", "ids_timeZone_EuropeMalta", "(UTC+01:00)"],
  ["BRT3BRST,M10.3.0/0,M2.3.0/0", "America/Sao Paulo", "ids_timeZone_AmericaSaoPaulo", "(UTC-03:00)"],
  ["EAT-3", "Africa/Khartoum", "ids_timeZone_AfricaKhartoum", "(UTC+03:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Tirane", "ids_timeZone_EuropeTirane", "(UTC+01:00)"],
  ["KGT-6", "Asia/Bishkek", "ids_timeZone_AsiaBishkek", "(UTC+06:00)"],
  ["HST10", "Pacific/Johnston", "ids_timeZone_PacificJohnston", "(UTC-10:00)"],
  ["GAMT9", "Pacific/Gambier", "ids_timeZone_PacificGambier", "(UTC-09:00)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/New York", "ids_timeZone_AmericaNewYork", "(UTC-05:00)"],
  ["EET-2EEST,M4.1.5/0,M10.5.5/0", "Asia/Damascus", "ids_timeZone_AsiaDamascus", "(UTC+02:00)"],
  ["IST-5:30", "Asia/Colombo", "ids_timeZone_AsiaColombo", "(UTC+05:30)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Brussels", "ids_timeZone_EuropeBrussels", "(UTC+01:00)"],
  ["TVT-12", "Pacific/Funafuti", "ids_timeZone_PacificFunafuti", "(UTC+12:00)"],
  ["GMT0", "America/Danmarkshavn", "ids_timeZone_AmericaDanmarkshavn", "(UTC+00:00)"],
  ["FJT-12", "Pacific/Fiji", "ids_timeZone_PacificFiji", "(UTC+12:00)"],
  ["BRT3", "America/Santarem", "ids_timeZone_AmericaSantarem", "(UTC-03:00)"],
  ["VET4:30", "America/Caracas", "ids_timeZone_AmericaCaracas", "(UTC-04:30)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Nassau", "ids_timeZone_AmericaNassau", "(UTC-05:00)"],
  ["TKT10", "Pacific/Fakaofo", "ids_timeZone_PacificFakaofo", "(UTC-10:00)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Detroit", "ids_timeZone_AmericaDetroit", "(UTC-05:00)"],
  ["VUT-11", "Pacific/Efate", "ids_timeZone_PacificEfate", "(UTC+11:00)"],
  ["CHUT-10", "Pacific/Chuuk", "ids_timeZone_PacificChuuk", "(UTC+10:00)"],
  ["CST6CDT,M3.2.0,M11.1.0", "America/North Dakota/Center", "ids_timeZone_AmericaNorthDakotaCenter", "(UTC-06:00)"],
  ["CHAST-12:45CHADT,M9.5.0/2:45,M4.1.0/3:45", "Pacific/Chatham", "ids_timeZone_PacificChatham", "(UTC+12:00)"],
  ["EST5", "America/Panama", "ids_timeZone_AmericaPanama", "(UTC-05:00)"],
  ["MYT-8", "Asia/Kuala Lumpur", "ids_timeZone_AsiaKualaLumpur", "(UTC+08:00)"],
  ["MeST8", "America/Metlakatla", "ids_timeZone_AmericaMetlakatla", "(UTC-08:00)"],
  ["PST8PDT,M3.2.0,M11.1.0", "America/Vancouver", "ids_timeZone_AmericaVancouver", "(UTC-08:00)"],
  ["CST6CDT,M3.2.0,M11.1.0", "America/Winnipeg", "ids_timeZone_AmericaWinnipeg", "(UTC-06:00)"],
  ["RET-4", "Indian/Reunion", "ids_timeZone_IndianReunion", "(UTC+04:00)"],
  ["EAT-3", "Indian/Mayotte", "ids_timeZone_IndianMayotte", "(UTC+03:00)"],
  ["SAKT-11", "Asia/Sakhalin", "Indian/Mayotte", "Indian/Mayotte", "ids_timeZone_AsiaSakhalin", "(UTC+11:00)"],
  ["AMT4", "America/Manaus", "ids_timeZone_AmericaManaus", "(UTC-04:00)"],
  ["UZT-5", "Asia/Tashkent", "ids_timeZone_AsiaTashkent", "(UTC+05:00)"],
  ["TFT-5", "Indian/Kerguelen", "ids_timeZone_IndianKerguelen", "(UTC+05:00)"],
  ["MST7", "America/Hermosillo", "ids_timeZone_AmericaHermosillo", "(UTC-07:00)"],
  ["GST-4", "Asia/Dubai", "ids_timeZone_AsiaDubai", "(UTC+04:00)"],
  ["EST-10EST,M10.1.0,M4.1.0/3", "Australia/Hobart", "ids_timeZone_AustraliaHobart", "(UTC+10:00)"],
  ["BRT3BRST,M10.3.0/0,M2.3.0/0", "America/Bahia", "ids_timeZone_AmericaBahia", "(UTC-03:00)"],
  ["CCT-6:30", "Indian/Cocos", "ids_timeZone_IndianCocos", "(UTC+06:30)"],
  ["LHST-10:30LHST-11,M10.1.0,M4.1.0", "Australia/Lord Howe", "ids_timeZone_AustraliaLordHowe", "(UTC+10:30)"],
  ["EAT-3", "Indian/Antananarivo", "ids_timeZone_IndianAntananarivo", "(UTC+03:00)"],
  ["ART3", "America/Argentina/Jujuy", "ids_timeZone_AmericaArgentinaJujuy", "(UTC-03:00)"],
  ["EAT-3", "Africa/Mogadishu", "ids_timeZone_AfricaMogadishu", "(UTC+03:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Zurich", "ids_timeZone_EuropeZurich", "(UTC+01:00)"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4", "Europe/Zaporozhye", "ids_timeZone_EuropeZaporozhye", "(UTC+02:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Zagreb", "ids_timeZone_EuropeZagreb", "(UTC+01:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Warsaw", "ids_timeZone_EuropeWarsaw", "(UTC+01:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Vienna", "ids_timeZone_EuropeVienna", "(UTC+01:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Vatican", "ids_timeZone_EuropeVatican", "(UTC+01:00)"],
  ["SBT-11", "Pacific/Guadalcanal", "ids_timeZone_PacificGuadalcanal", "(UTC+11:00)"],
  ["AKST9AKDT,M3.2.0,M11.1.0", "America/Nome", "ids_timeZone_AmericaNome", "(UTC-09:00)"],
  ["PST8", "Pacific/Pitcairn", "ids_timeZone_PacificPitcairn", "(UTC-08:00)"],
  ["ART3", "America/Argentina/San Juan", "ids_timeZone_AmericaArgentinaSanJuan", "(UTC-03:00)"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4", "Europe/Kiev", "ids_timeZone_EuropeKiev", "(UTC+02:00)"],
  ["CST6CDT,M4.1.0,M10.5.0", "America/Mexico City", "ids_timeZone_AmericaMexicoCity", "(UTC-06:00)"],
  ["AST-3", "Asia/Aden", "ids_timeZone_AsiaAden", "(UTC+03:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Skopje", "ids_timeZone_EuropeSkopje", "(UTC+01:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/San Marino", "ids_timeZone_EuropeSanMarino", "(UTC+01:00)"],
  ["AST4", "America/Kralendijk", "ids_timeZone_AmericaKralendijk", "(UTC-04:00)"],
  ["CST6", "America/Swift Current", "ids_timeZone_AmericaSwiftCurrent", "(UTC-06:00)"],
  ["CAT-2", "Africa/Maputo", "ids_timeZone_AfricaMaputo", "(UTC+02:00)"],
  ["AST4ADT,M3.2.0,M11.1.0", "Atlantic/Bermuda", "ids_timeZone_AtlanticBermuda", "(UTC-04:00)"],
  ["DDUT-10", "Antarctica/DumontDUrville", "ids_timeZone_AntarcticaDumontDUrville", "(UTC+10:00)"],
  ["SAMT-4", "Europe/Samara", "ids_timeZone_EuropeSamara", "(UTC+04:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Rome", "ids_timeZone_EuropeRome", "(UTC+01:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Prague", "ids_timeZone_EuropePrague", "(UTC+01:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Oslo", "ids_timeZone_EuropeOslo", "(UTC+01:00)"],
  ["MSK-4", "Europe/Moscow", "ids_timeZone_EuropeMoscow", "(UTC+04:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Monaco", "ids_timeZone_EuropeMonaco", "(UTC+01:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Luxembourg", "ids_timeZone_EuropeLuxembourg", "(UTC+01:00)"],
  ["PST8PDT,M4.1.0,M10.5.0", "America/Santa Isabel", "ids_timeZone_AmericaSantaIsabel", "(UTC-08:00)"],
  ["GMT0BST,M3.5.0/1,M10.5.0", "Europe/London", "ids_timeZone_EuropeLondon", "(UTC+00:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Ljubljana", "ids_timeZone_EuropeLjubljana", "(UTC+01:00)"],
  ["WET0WEST,M3.5.0/1,M10.5.0", "Europe/Lisbon", "ids_timeZone_EuropeLisbon", "(UTC+00:00)"],
  ["VLAT-11", "Asia/Vladivostok", "ids_timeZone_AsiaVladivostok", "(UTC+11:00)"],
  ["GMT0BST,M3.5.0/1,M10.5.0", "Europe/Jersey", "ids_timeZone_EuropeJersey", "(UTC+00:00)"],
  ["NZST-12NZDT,M9.5.0,M4.1.0/3", "Antarctica/South Pole", "ids_timeZone_AntarcticaSouthPole", "(UTC+12:00)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Grand Turk", "ids_timeZone_AmericaGrandTurk", "(UTC-05:00)"],
  ["AKST9AKDT,M3.2.0,M11.1.0", "America/Anchorage", "ids_timeZone_AmericaAnchorage", "(UTC-09:00)"],
  ["CST6", "America/Managua", "ids_timeZone_AmericaManagua", "(UTC-06:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Belgrade", "ids_timeZone_EuropeBelgrade", "(UTC+01:00)"],
  ["AST4", "America/Montserrat", "ids_timeZone_AmericaMontserrat", "(UTC-04:00)"],
  ["EAT-3", "Indian/Comoro", "ids_timeZone_IndianComoro", "(UTC+03:00)"],
  ["GMT0", "Africa/Bissau", "ids_timeZone_AfricaBissau", "(UTC+00:00)"],
  ["AQTT-5", "Asia/Aqtau", "ids_timeZone_AsiaAqtau", "(UTC+05:00)"],
  ["CST6", "America/Tegucigalpa", "ids_timeZone_AmericaTegucigalpa", "(UTC-06:00)"],
  ["CIT-8", "Asia/Makassar", "ids_timeZone_AsiaMakassar", "(UTC+08:00)"],
  ["ECT5", "America/Guayaquil", "ids_timeZone_AmericaGuayaquil", "(UTC-05:00)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Indiana/Marengo", "ids_timeZone_AmericaIndianaMarengo", "(UTC-05:00)"],
  ["ULAT-8", "Asia/Ulaanbaatar", "ids_timeZone_AsiaUlaanbaatar", "(UTC+08:00)"],
  ["CST6CDT,M3.2.0,M11.1.0", "America/North Dakota/Beulah", "ids_timeZone_AmericaNorthDakotaBeulah", "(UTC-06:00)"],
  ["MAGT-12", "Asia/Magadan", "ids_timeZone_AsiaMagadan", "(UTC+12:00)"],
  ["GMT0", "Africa/Abidjan", "ids_timeZone_AfricaAbidjan", "(UTC+00:00)"],
  ["AMT4", "America/Porto Velho", "ids_timeZone_AmericaPortoVelho", "(UTC-04:00)"],
  ["CAT-2", "Africa/Lubumbashi", "ids_timeZone_AfricaLubumbashi", "(UTC+02:00)"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4", "Europe/Chisinau", "ids_timeZone_EuropeChisinau", "(UTC+02:00)"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4", "Europe/Bucharest", "ids_timeZone_EuropeBucharest", "(UTC+02:00)"],
  ["GALT6", "Pacific/Galapagos", "ids_timeZone_PacificGalapagos", "(UTC-06:00)"],
  ["CST6CDT,M4.1.0,M10.5.0", "America/Cancun", "ids_timeZone_AmericaCancun", "(UTC-06:00)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Indiana/Petersburg", "ids_timeZone_AmericaIndianaPetersburg", "(UTC-05:00)"],
  ["UZT-5", "Asia/Samarkand", "ids_timeZone_AsiaSamarkand", "(UTC+05:00)"],
  ["IRKT-9", "Asia/Irkutsk", "ids_timeZone_AsiaIrkutsk", "(UTC+09:00)"],
  ["CST-8", "Asia/Harbin", "ids_timeZone_AsiaHarbin", "(UTC+08:00)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Thunder Bay", "ids_timeZone_AmericaThunderBay", "(UTC-05:00)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Pangnirtung", "ids_timeZone_AmericaPangnirtung", "(UTC-05:00)"],
  ["AST4", "America/Santo Domingo", "ids_timeZone_AmericaSantoDomingo", "(UTC-04:00)"],
  ["AST4", "America/Puerto Rico", "ids_timeZone_AmericaPuertoRico", "(UTC-04:00)"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4", "Europe/Istanbul", "ids_timeZone_EuropeIstanbul", "(UTC+02:00)"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4", "Europe/Athens", "ids_timeZone_EuropeAthens", "(UTC+02:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Andorra", "ids_timeZone_EuropeAndorra", "(UTC+01:00)"],
  ["NOVT-7", "Asia/Novokuznetsk", "ids_timeZone_AsiaNovokuznetsk", "(UTC+07:00)"],
  ["EST-10EST,M10.1.0,M4.1.0/3", "Australia/Sydney", "ids_timeZone_AustraliaSydney", "(UTC+10:00)"],
  ["VOST-6", "Antarctica/Vostok", "ids_timeZone_AntarcticaVostok", "(UTC+06:00)"],
  ["AFT-4:30", "Asia/Kabul", "ids_timeZone_AsiaKabul", "(UTC+04:30)"],
  ["EST-10", "Australia/Lindeman", "ids_timeZone_AustraliaLindeman", "(UTC+10:00)"],
  ["PST8PDT,M3.2.0,M11.1.0", "America/Whitehorse","ids_timeZone_AmericaWhitehorse", "(UTC-08:00)"],
  ["EST-10EST,M10.1.0,M4.1.0/3", "Australia/Melbourne", "ids_timeZone_AustraliaMelbourne", "(UTC+10:00)"],
  ["EAT-3", "Africa/Juba", "ids_timeZone_AfricaJuba", "(UTC+03:00)"],
  ["CAT-2", "Africa/Kigali", "ids_timeZone_AfricaKigali", "(UTC+02:00)"],
  ["GMT0BST,M3.5.0/1,M10.5.0", "Europe/Isle of Man", "ids_timeZone_EuropeIsleOfMan", "(UTC+00:00)"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4", "Europe/Tallinn", "ids_timeZone_EuropeTallinn", "(UTC+02:00)"],
  ["PKT-5", "Asia/Karachi", "ids_timeZone_AsiaKarachi", "(UTC+05:00)"],
  ["EAT-3", "Africa/Addis Ababa", "ids_timeZone_AfricaAddisAbaba", "(UTC+03:00)"],
  ["EST-10EST,M10.1.0,M4.1.0/3", "Australia/Currie", "ids_timeZone_AustraliaCurrie", "(UTC+10:00)"],
  ["CST-9:30CST,M10.1.0,M4.1.0/3", "Australia/Broken Hill", "ids_timeZone_AustraliaBrokenHill", "(UTC+09:30)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Kentucky/Monticello", "ids_timeZone_AmericaKentuckyMonticello", "(UTC-05:00)"],
  ["BNT-8", "Asia/Brunei", "ids_timeZone_AsiaBrunei", "(UTC+08:00)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Montreal", "ids_timeZone_AmericaMontreal", "(UTC-05:00)"],
  ["WAT-1", "Africa/Porto-Novo", "ids_timeZone_AfricaPortoNovo", "(UTC+01:00)"],
  ["CST-9:30CST,M10.1.0,M4.1.0/3", "Australia/Adelaide", "ids_timeZone_AustraliaAdelaide", "(UTC+09:30)"],
  ["FKT4FKST,M9.1.0,M4.3.0", "Atlantic/Stanley", "ids_timeZone_AtlanticStanley", "(UTC-04:00)"],
  ["GMT0", "Africa/Accra", "ids_timeZone_AfricaAccra", "(UTC+00:00)"],
  ["WET0WEST,M3.5.0/1,M10.5.0", "Atlantic/Madeira", "ids_timeZone_AtlanticMadeira", "(UTC+00:00)"],
  ["DAVT-7", "Antarctica/Davis", "ids_timeZone_AntarcticaDavis", "(UTC+07:00)"],
  ["AMT-4AMST,M3.5.0,M10.5.0/3", "Asia/Yerevan", "ids_timeZone_AsiaYerevan", "(UTC+04:00)"],
  ["SAST-2", "Africa/Maseru", "ids_timeZone_AfricaMaseru", "(UTC+02:00)"],
  ["CAT-2", "Africa/Harare", "ids_timeZone_AfricaHarare", "(UTC+02:00)"],
  ["YAKT-10", "Asia/Yakutsk", "ids_timeZone_AsiaYakutsk", "(UTC+10:00)"],
  ["SST11", "Pacific/Pago Pago", "ids_timeZone_PacificPagoPago", "(UTC-11:00)"],
  ["WIT-7", "Asia/Pontianak", "ids_timeZone_AsiaPontianak", "(UTC+07:00)"],
  ["NZST-12NZDT,M9.5.0,M4.1.0/3", "Antarctica/McMurdo", "ids_timeZone_AntarcticaMcMurdo", "(UTC+12:00)"],
  ["KST-9", "Asia/Pyongyang", "ids_timeZone_AsiaPyongyang", "(UTC+09:00)"],
  ["AST-3", "Asia/Riyadh", "ids_timeZone_AsiaRiyadh", "(UTC+03:00)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Kentucky/Louisville", "ids_timeZone_AmericaKentuckyLouisville", "(UTC-05:00)"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4", "Europe/Helsinki", "ids_timeZone_EuropeHelsinki", "(UTC+02:00)"],
  ["WAT-1", "Africa/Brazzaville", "ids_timeZone_AfricaBrazzaville", "(UTC+01:00)"],
  ["EAT-3", "Africa/Nairobi", "ids_timeZone_AfricaNairobi", "(UTC+03:00)"],
  ["AKST9AKDT,M3.2.0,M11.1.0", "America/Sitka", "ids_timeZone_AmericaSitka", "(UTC-09:00)"],
  ["JST-9", "Asia/Tokyo", "ids_timeZone_AsiaTokyo", "(UTC+09:00)"],
  ["AZT-4AZST,M3.5.0/4,M10.5.0/5", "Asia/Baku", "ids_timeZone_AsiaBaku", "(UTC+04:00)"],
  ["AST4ADT,M3.2.0,M11.1.0", "America/Glace Bay", "ids_timeZone_AmericaGlaceBay", "(UTC-04:00)"],
  ["EST5", "America/Jamaica", "ids_timeZone_AmericaJamaica", "(UTC-05:00)"],
  ["CST5CDT,M3.2.0/0,M10.5.0/1", "America/Havana", "ids_timeZone_AmericaHavana", "(UTC-05:00)"],
  ["AKST9AKDT,M3.2.0,M11.1.0", "America/Juneau", "ids_timeZone_AmericaJuneau", "(UTC-09:00)"],
  ["SGT-8", "Asia/Singapore", "ids_timeZone_AsiaSingapore", "(UTC+08:00)"],
  ["BRT3", "America/Araguaina", "ids_timeZone_AmericaAraguaina", "(UTC-03:00)"],
  ["MART9:30", "Pacific/Marquesas", "ids_timeZone_PacificMarquesas", "(UTC-09:30)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Bratislava", "ids_timeZone_EuropeBratislava", "(UTC+01:00)"],
  ["CST-8", "Asia/Urumqi", "ids_timeZone_AsiaUrumqi", "(UTC+08:00)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Nipigon", "ids_timeZone_AmericaNipigon", "(UTC-05:00)"],
  ["MMT-6:30", "Asia/Rangoon", "ids_timeZone_AsiaRangoon", "(UTC+06:30)"],
  ["UYT3UYST,M10.1.0,M3.2.0", "America/Montevideo", "ids_timeZone_AmericaMontevideo", "(UTC-03:00)"],
  ["SAST-2", "Africa/Mbabane", "ids_timeZone_AfricaMbabane", "(UTC+02:00)"],
  ["ICT-7", "Asia/Ho Chi Minh", "ids_timeZone_AsiaHoChiMinh", "(UTC+07:00)"],
  ["ICT-7", "Asia/Phnom Penh", "ids_timeZone_AsiaPhnomPenh", "(UTC+07:00)"],
  ["AST4", "America/Lower Princes", "ids_timeZone_AmericaLowerPrinces", "(UTC-04:00)"],
  ["MST7MDT,M4.1.0,M10.5.0", "America/Chihuahua", "ids_timeZone_AmericaChihuahua", "(UTC-07:00)"],
  ["NOVT-7", "Asia/Novosibirsk", "ids_timeZone_AsiaNovosibirsk", "(UTC+07:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Amsterdam", "ids_timeZone_EuropeAmsterdam", "(UTC+01:00)"],
  ["CST6CDT,M3.2.0,M11.1.0", "America/Indiana/Knox", "ids_timeZone_AmericaIndianaKnox", "(UTC-06:00)"],
  ["GST-4", "Asia/Muscat", "ids_timeZone_AsiaMuscat", "(UTC+04:00)"],
  ["PHT-8", "Asia/Manila", "ids_timeZone_AsiaManila", "(UTC+08:00)"],
  ["AST4", "America/Blanc-Sablon", "ids_timeZone_AmericaBlancSablon", "(UTC-04:00)"],
  ["GMT0BST,M3.5.0/1,M10.5.0", "Europe/Guernsey", "ids_timeZone_EuropeGuernsey", "(UTC+00:00)"],
  ["AST4", "America/St Kitts", "ids_timeZone_AmericaStKitts", "(UTC-04:00)"],
  ["AST4", "America/Martinique", "ids_timeZone_AmericaMartinique", "(UTC-04:00)"],
  ["EIT-9", "Asia/Jayapura", "ids_timeZone_AsiaJayapura", "(UTC+09:00)"],
  ["KRAT-8", "Asia/Krasnoyarsk", "ids_timeZone_AsiaKrasnoyarsk", "(UTC+08:00)"],
  ["SRT3", "America/Paramaribo", "ids_timeZone_AmericaParamaribo", "(UTC-03:00)"],
  ["AMT4", "America/Boa Vista", "ids_timeZone_AmericaBoaVista", "(UTC-04:00)"],
  ["IST-5:30", "Asia/Kolkata", "ids_timeZone_AsiaKolkata", "(UTC+05:30)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Indiana/Indianapolis", "ids_timeZone_AmericaIndianaIndianapolis", "(UTC-05:00)"],
  ["NPT-5:45", "Asia/Kathmandu", "ids_timeZone_AsiaKathmandu", "(UTC+05:45)"],
  ["NST3:30NDT,M3.2.0,M11.1.0", "America/St Johns", "ids_timeZone_AmericaStJohns", "(UTC-03:30)"],
  ["GMT0", "Atlantic/Reykjavik", "ids_timeZone_AtlanticReykjavik", "(UTC+00:00)"],
  ["CST6CDT,M3.2.0,M11.1.0", "America/Matamoros", "ids_timeZone_AmericaMatamoros", "(UTC-06:00)"],
  ["NZST-12NZDT,M9.5.0,M4.1.0/3", "Pacific/Auckland", "ids_timeZone_PacificAuckland", "(UTC+12:00)"],
  ["MIST-11", "Antarctica/Macquarie", "ids_timeZone_AntarcticaMacquarie", "(UTC+11:00)"],
  ["ART3", "America/Argentina/Catamarca", "ids_timeZone_AmericaArgentinaCatamarca", "(UTC-03:00)"],
  ["CST6CDT,M4.1.0,M10.5.0", "America/Merida", "ids_timeZone_AmericaMerida", "(UTC-06:00)"],
  ["WAT-1", "Africa/Niamey", "ids_timeZone_AfricaNiamey", "(UTC+01:00)"],
  ["AST4ADT,M3.2.0,M11.1.0", "America/Halifax", "ids_timeZone_AmericaHalifax", "(UTC-04:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Africa/Ceuta", "ids_timeZone_AfricaCeuta", "(UTC+01:00)"],
  ["CST6CDT,M3.2.0,M11.1.0", "America/Chicago", "ids_timeZone_AmericaChicago", "(UTC-06:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Stockholm", "ids_timeZone_EuropeStockholm", "(UTC+01:00)"],
  ["ICT-7", "Asia/Vientiane", "ids_timeZone_AsiaVientiane", "(UTC+07:00)"],
  ["GMT0", "Africa/Conakry", "ids_timeZone_AfricaConakry", "(UTC+00:00)"],
  ["ART3", "America/Argentina/Tucuman", "ids_timeZone_AmericaArgentinaTucuman", "(UTC-03:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Berlin", "ids_timeZone_EuropeBerlin", "(UTC+01:00)"],
  ["EET-2EEST,M3.5.0/3,M10.5.0/4", "Asia/Nicosia", "ids_timeZone_AsiaNicosia", "(UTC+02:00)"],
  ["GMT0", "Africa/Dakar", "ids_timeZone_AfricaDakar", "(UTC+00:00)"],
  ["CAT-2", "Africa/Lusaka", "ids_timeZone_AfricaLusaka", "(UTC+02:00)"],
  ["EST5", "America/Cayman", "ids_timeZone_AmericaCayman", "(UTC-05:00)"],
  ["EET-2", "Asia/Gaza", "ids_timeZone_AsiaGaza", "(UTC+02:00)"],
  ["GET-4", "Asia/Tbilisi", "ids_timeZone_AsiaTbilisi", "(UTC+04:00)"],
  ["EST5", "America/Atikokan", "ids_timeZone_AmericaAtikokan", "(UTC-05:00)"],
  ["BDT-6", "Asia/Dhaka", "ids_timeZone_AsiaDhaka", "(UTC+06:00)"],
  ["PST8PDT,M3.2.0,M11.1.0", "America/Tijuana", "ids_timeZone_AmericaTijuana", "(UTC-08:00)"],
  ["WAT-1", "Africa/Douala", "ids_timeZone_AfricaDouala", "(UTC+01:00)"],
  ["BRT3", "America/Maceio", "ids_timeZone_AmericaMaceio", "(UTC-03:00)"],
  ["EST-10", "Australia/Brisbane", "ids_timeZone_AustraliaBrisbane", "(UTC+10:00)"],
  ["HST10", "Pacific/Honolulu", "ids_timeZone_PacificHonolulu", "(UTC-10:00)"],
  ["ART3", "America/Argentina/Mendoza", "ids_timeZone_AmericaArgentinaMendoza", "(UTC-03:00)"],
  ["AMT4AMST,M10.3.0/0,M2.3.0/0", "America/Cuiaba", "ids_timeZone_AmericaCuiaba", "(UTC-04:00)"],
  ["BOT4", "America/La Paz", "ids_timeZone_AmericaLaPaz", "(UTC-04:00)"],
  ["GMT0", "Africa/Ouagadougou", "ids_timeZone_AfricaOuagadougou", "(UTC+00:00)"],
  ["FNT2", "America/Noronha", "ids_timeZone_AmericaNoronha", "(UTC-02:00)"],
  ["PST8PDT,M3.2.0,M11.1.0", "America/Los Angeles", "ids_timeZone_AmericaLosAngeles", "(UTC-08:00)"],
  ["ART3", "America/Argentina/Buenos Aires", "ids_timeZone_AmericaArgentinaBuenosAires", "(UTC-03:00)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Toronto", "ids_timeZone_AmericaToronto", "(UTC-05:00)"],
  ["AST4", "America/Grenada", "ids_timeZone_AmericaGrenada", "(UTC-04:00)"],
  ["EAT-3", "Africa/Kampala", "ids_timeZone_AfricaKampala", "(UTC+03:00)"],
  ["AST4", "America/St Vincent", "ids_timeZone_AmericaStVincent", "(UTC-04:00)"],
  ["GMT0", "Africa/Freetown", "ids_timeZone_AfricaFreetown", "(UTC+00:00)"],
  ["EST5EDT,M3.2.0,M11.1.0", "America/Iqaluit", "ids_timeZone_AmericaIqaluit", "(UTC-05:00)"],
  ["HOVT-7", "Asia/Hovd", "ids_timeZone_AsiaHovd", "(UTC+07:00)"],
  ["COT5", "America/Bogota", "ids_timeZone_AmericaBogota", "(UTC-05:00)"],
  ["BRT3", "America/Belem", "ids_timeZone_AmericaBelem", "(UTC-03:00)"],
  ["CET-1CEST,M3.5.0,M10.5.0/3", "Europe/Copenhagen", "ids_timeZone_EuropeCopenhagen", "(UTC+01:00)"],
  ["SAST-2", "Africa/Johannesburg", "ids_timeZone_AfricaJohannesburg", "(UTC+02:00)"],
  ["GILT-12", "Pacific/Tarawa", "ids_timeZone_PacificTarawa", "(UTC+12:00)"],
  ["GMT0", "Africa/Monrovia", "ids_timeZone_AfricaMonrovia", "(UTC+00:00)"],
  ["TJT-5", "Asia/Dushanbe", "ids_timeZone_AsiaDushanbe", "(UTC+05:00)"],
  ["GYT4", "America/Guyana", "ids_timeZone_AmericaGuyana", "(UTC-04:00)"],
  ["HKT-8", "Asia/Hong Kong", "ids_timeZone_AsiaHongKong", "(UTC+08:00)"]
];

/*Language*/
sys.allLanguage = {
  al: 'Shqipe',
  ar: 'العربية',
  br: 'Português(Brasil)',
  bu: 'български',
  ch: '简体中文',
  du: 'Nederlands',
  en: 'English',
  en_uk: 'English(UK)',
  en_us: 'English(US)',
  fr: 'Français',
  de: 'Deutsch',
  gk: 'Ελληνικά',
  hg: 'Magyar',
  it: 'Italiano',
  ja: '日本語',
  mk: 'Македонија',
  pg: 'Português(Portugal)',
  po: 'Polski',
  ro: 'Română',
  ru: 'Русский',
  sp: 'Español',
  sp_latam: 'Español(Latam)',
  sr: 'Srpski',
  tw: '繁體中文',
  ur: 'Українська',
  da: 'Dansk',
  kz: 'Қазақша',
  kr: '한글',
  th: 'ไทย',
  cs: 'čeština',
  hr: 'Hrvatski',
  se: 'Sverige',
  sk: 'Slovensko',
  wr: 'اردو',
  vi: 'Vietnamese',
  tr: 'Turkish',
  si: 'Slovenian',
  fi: 'Suomi',
  no: 'Norge',
  ee: 'eesti',
  fa: 'فارسی',
  lv: 'Latvijas',
  lt: 'Lietuvos',
  id: 'Indonesia'
};
sys.Language = [
  ['en', 'English'],
  ['fr', 'Français'],
  ['it', 'Italiano'],
  ['sp', 'Español']
];
sys.customLanguage = [];
sys.NtpServer1 = [
  ["0.openwrt.pool.ntp.org", "0.openwrt.pool.ntp.org"],
  ["1.openwrt.pool.ntp.org", "1.openwrt.pool.ntp.org"],
  ["0.asia.pool.ntp.org", "0.asia.pool.ntp.org"],
  ["1.asia.pool.ntp.org", "1.asia.pool.ntp.org"],
  ["0.europe.pool.ntp.org", "0.europe.pool.ntp.org"],
  ["1.europe.pool.ntp.org", "1.europe.pool.ntp.org"],
  ["0.africa.pool.ntp.org", "0.africa.pool.ntp.org"],
  ["1.africa.pool.ntp.org", "1.africa.pool.ntp.org"],
  ["0.north-america.pool.ntp.org", "0.north-america.pool.ntp.org"],
  ["1.north-america.pool.ntp.org", "1.north-america.pool.ntp.org"],
  ["0.oceania.pool.ntp.org", "0.oceania.pool.ntp.org"],
  ["1.oceania.pool.ntp.org", "1.oceania.pool.ntp.org"],
  ["0.south-america.pool.ntp.org", "0.south-america.pool.ntp.org"],
  ["1.south-america.pool.ntp.org", "1.south-america.pool.ntp.org"]
];
sys.NtpServer2 = [
  ["0.openwrt.pool.ntp.org", "0.openwrt.pool.ntp.org"],
  ["1.openwrt.pool.ntp.org", "1.openwrt.pool.ntp.org"],
  ["0.asia.pool.ntp.org", "0.asia.pool.ntp.org"],
  ["1.asia.pool.ntp.org", "1.asia.pool.ntp.org"],
  ["0.europe.pool.ntp.org", "0.europe.pool.ntp.org"],
  ["1.europe.pool.ntp.org", "1.europe.pool.ntp.org"],
  ["0.africa.pool.ntp.org", "0.africa.pool.ntp.org"],
  ["1.africa.pool.ntp.org", "1.africa.pool.ntp.org"],
  ["0.north-america.pool.ntp.org", "0.north-america.pool.ntp.org"],
  ["1.north-america.pool.ntp.org", "1.north-america.pool.ntp.org"],
  ["0.oceania.pool.ntp.org", "0.oceania.pool.ntp.org"],
  ["1.oceania.pool.ntp.org", "1.oceania.pool.ntp.org"],
  ["0.south-america.pool.ntp.org", "0.south-america.pool.ntp.org"],
  ["1.south-america.pool.ntp.org", "1.south-america.pool.ntp.org"]
];
sys.service_Provider = [
  ["dtdns.com", "dtdns.com"],
  ["dyndns.org", "dyndns.org"],
  ["no-ip.com", "no-ip.com"],
  ["changeip.com", "changeip.com"]
];


export default sys;
